---
- hosts: app
  become: yes
  vars:
    zabbix_version: 6.0
    zbx_srv: 172.16.77.140
    ubuntu16_link: "https://repo.zabbix.com/zabbix/{{zabbix_version}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zabbix_version}}-1+ubuntu16.04_all.deb"
    ubuntu16_file: "zabbix-release_{{zabbix_version}}-1+ubuntu16.04_all.deb"
    ubuntu18_link: "https://repo.zabbix.com/zabbix/{{zabbix_version}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zabbix_version}}-1+ubuntu18.04_all.deb"
    ubuntu18_file: "zabbix-release_{{zabbix_version}}-1+ubuntu18.04_all.deb"
    ubuntu20_link: "https://repo.zabbix.com/zabbix/{{zabbix_version}}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{zabbix_version}}-1+ubuntu20.04_all.deb"
    ubuntu20_file: "zabbix-release_{{zabbix_version}}-1+ubuntu20.04_all.deb"
  roles:
   - zabbix.agent
